FROM gcr.io/google_appengine/base
LABEL maintainer='Codeship Inc., <maintainers@codeship.com>'

# This is loosely based on the Dockerfile for the google/cloud-sdk image available
# at https://hub.docker.com/r/google/cloud-sdk/~/dockerfile/

RUN apt-get update
